# fly.toml app configuration file generated for little-hill-1921 on 2023-08-06T22:14:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "little-hill-1921"
primary_region = "ewr"

[env]
  PORT = "8080" 

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
